openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/temperatura:
    x-router-controller: temperaturaController
    get:
      description: Returns all teams
      operationId: getTemperaturas
      responses:
        200:
          description: temperatura list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/temperatura'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
                
  /api/v1/temperatura/{id}:
    x-router-controller: temperaturaController
    get:
      description: Returns a single team by its id
      operationId: findByid
      parameters:
        - required: true
          name: id
          description: id of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: temperatura found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/temperatura'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    temperatura:
        type: object
        required:
          - id
        properties:
          date:
            type: number
          id:
            type: number
          stations_id:
            type: number
          maxtemp:
            type: number
          mintemp:
            type: number
          averagetemp:
            type: number
          location:
            type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true